//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SoundSpace.rc
//
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDD_ABOUTBOX                    100
#define IDD_SOUNDSPACE_FORM             101
#define IDR_MAINFRAME                   128
#define IDR_SOUNDSTYPE                  129
#define IDD_SETTINGS_TIME               130
#define IDD_PREFPAGE_FADETIMES          130
#define IDD_SETTINGS_AUDIO              132
#define IDD_PREFPAGE_AUDIO              132
#define IDD_LAYER_SETUP                 133
#define IDD_STREAM_DEVICES              133
#define IDD_LIST_DEVICES                134
#define IDD_DEVICES_AUDIO               134
#define IDD_SETTINGS_STARTSTOP          135
#define IDD_LIST_STREAMS                136
#define IDD_STREAM_BASIC                138
#define IDD_STREAM_RAMPS                139
#define IDD_LIST_VALUES                 141
#define IDD_VALUE_FLOAT                 143
#define IDD_VALUE_CLOCK                 144
#define IDD_VALUE_DATE                  145
#define IDD_VALUE_MAP                   146
#define IDD_VALUE_ADD                   147
#define IDD_VALUE_PRODUCT               148
#define IDD_VALUE_CONDITIONAL           149
#define IDD_VALUE_RANDOM                150
#define IDD_LIST_CONDITIONALS           151
#define IDD_COND_BOOLEAN                153
#define IDD_COND_RELATION               154
#define IDD_COND_RANGE                  155
#define IDD_COND_TIMEINT                157
#define IDD_COND_TIMERELATION           158
#define IDD_COND_MINUTES                159
#define IDD_COND_DATEINT                160
#define IDD_COND_AND                    161
#define IDD_COND_OPERATION              161
#define IDD_COND_OR                     162
#define IDD_COND_NOT                    163
#define IDD_LIST_OBJECTS                164
#define IDD_OBJECT_WAVFILE              166
#define IDD_OBJECT_AUDIOFILE            166
#define IDD_OBJECT_MIDIFILE             167
#define IDD_OBJECT_DSFILE               168
#define IDD_OBJECT_SILENCE              169
#define IDD_OBJECT_SIMULTANEOUS         170
#define IDD_OBJECT_SEQUENTIAL           171
#define IDD_OBJECT_RANDOM               172
#define IDD_OBJECT_CHAIN                173
#define IDD_OBJECT_CONDITIONAL          176
#define IDD_LIST_TASKS                  177
#define IDD_TASK_EDITOR                 179
#define IDD_EVENT_CONDMESSAGE           181
#define IDD_DEVICES_MIDI                181
#define IDD_EVENT_PLAYMESSAGE           182
#define IDD_LIST_MESSAGES               183
#define IDD_MESSAGE_LOAD                185
#define IDD_MESSAGE_SOLO                186
#define IDD_MESSAGE_START               187
#define IDD_MESSAGE_TRIGGERED           188
#define IDD_MESSAGE_CLOCK               190
#define IDD_OBJECT_MIDILIST             192
#define IDD_COND_PLAYING                193
#define IDD_MESSAGE_VOLUME              194
#define IDD_OBJECT_DISTRIBUTION         195
#define IDD_MESSAGE_DIALOG              198
#define IDD_LAYOUT_DIALOG               202
#define IDD_OBJECT_DMXSELECTFILE        205
#define IDD_VALUE_INPUTRANGE            206
#define IDD_OBJECT_LINEARSELECT         207
#define IDD_AUTOSTART_DLG               208
#define IDD_VALUE_OPERATION             209
#define ID_DEVICES_AUDIO                210
#define ID_DEVICES_MIDI                 211
#define ID_DEVICES_DMX                  212
#define ID_TASKLIST_INITIAL             213
#define ID_TASKLIST_TRIGGERED           214
#define ID_TASKLIST_TIME                215
#define IDD_DEVICES_DMX                 217
#define IDD_EDIT_VALUE                  218
#define IDD_EDIT_COMBO                  218
#define ID_SETTINGS_FILEPATHS           219
#define IDD_SETTINGS_FILEPATH           220
#define IDD_PREFPAGE_FILEPATH           220
#define ID_FILE_EXPORT                  221
#define ID_EXPORT_ASCIIDUMP             222
#define ID_EXPORT_CONFIGERRORS          223
#define ID_EXPORT_RUN                   224
#define IDD_LIST_INPUTS                 225
#define IDD_INPUT_ICPANALOG             227
#define IDD_DIALOG1                     228
#define IDD_INPUT_ICPDIGITAL            228
#define ID_EDIT_INPUTS                  229
#define IDD_INPUT_PARALLEL              230
#define IDD_COND_DAYOFWEEK              231
#define IDD_INPUT_MIDIEVENT             232
#define IDD_MSGLIST_COND                235
#define IDD_EDIT_CONTROL                236
#define IDD_MSGLIST_CLOCK               237
#define IDD_EDIT_CLOCK                  238
#define IDD_MSGLIST_TRIGGER             239
#define IDD_SETTINGS_RESET              240
#define IDD_PREFPAGE_RESOLUTION         241
#define IDD_PREFPAGE_UPDATES            242
#define IDD_DIALOG2                     243
#define IDD_WATCHDOG_RUNDLG             243
#define IDD_LIST_STRINGS                245
#define IDD_STRING_SIMPLE               247
#define IDD_STRING_CONCAT               248
#define IDD_STRING_ALPHABET             249
#define IDD_OBJECT_SETSTATE             250
#define IDC_BITS                        1006
#define IDC_FREQUENCY                   1007
#define IDC_MIDI_RESOLUTION             1009
#define IDC_DS_RESOLUTION               1010
#define IDC_BUFFER_LENGTH               1011
#define IDC_LAYERS                      1011
#define IDC_EVENT_RES                   1011
#define IDC_BUFFER_UPDATE               1012
#define IDC_SELECT_LAYER                1012
#define IDC_TIMESTEP                    1013
#define IDC_LAYER_SPIN                  1013
#define IDC_EVENTSTEP                   1013
#define IDC_TRIGGERSTEP                 1014
#define IDC_CLOCKSTEP                   1015
#define IDC_LAYER_NAME                  1015
#define IDC_STREAM_NAME                 1015
#define IDC_STEREO                      1016
#define IDC_CLOCKSTEP2                  1016
#define IDC_GUISTEP                     1016
#define IDC_MONO                        1017
#define IDC_LEFT_CHANNEL                1018
#define IDC_RIGHT_CHANNEL               1019
#define IDC_CHANNELS                    1020
#define IDC_BUFFERS                     1021
#define IDC_PLAY_BUFFERS                1021
#define IDC_WAIT_BUFFERS                1022
#define IDC_MIDIOUT_DEVICE              1022
#define IDC_AUDIO_DEVICE                1023
#define IDC_VOLUME_DEVICE               1024
#define IDC_START                       1025
#define IDC_MIDIIN_DEVICE               1025
#define IDC_STOP                        1026
#define IDC_TIME                        1027
#define IDC_DATE                        1028
#define IDC_EXT_VALUE1                  1029
#define IDC_EXT_VALUE2                  1030
#define IDC_EXT_VALUE3                  1031
#define IDC_EXT_VALUE4                  1032
#define IDC_EXT_VALUE5                  1033
#define IDC_EXT_VALUE6                  1034
#define IDC_EXT_VALUE7                  1035
#define IDC_EXT_VALUE8                  1036
#define IDC_EXT_VALUE9                  1037
#define IDC_EXT_VALUE10                 1038
#define IDC_EXT_VALUE11                 1039
#define IDC_EXT_VALUE12                 1040
#define IDC_EXT_VALUE13                 1041
#define IDC_EXT_VALUE14                 1042
#define IDC_EXT_VALUE15                 1043
#define IDC_EXT_VALUE16                 1044
#define IDC_LAYER_VOLUME0               1047
#define IDC_LAYER_VOLUME1               1048
#define IDC_LAYER_VOLUME2               1049
#define IDC_LAYER_VOLUME3               1050
#define IDC_LAYER_VOLUME4               1051
#define IDC_LAYER_VOLUME5               1052
#define IDC_LAYER_VOLUME6               1053
#define IDC_LAYER_VOLUME7               1054
#define IDC_LAYER_VOLUME8               1055
#define IDC_LAYER_TXT0                  1057
#define IDC_LAYER_TXT1                  1058
#define IDC_LAYER_TXT2                  1059
#define IDC_LAYER_TXT3                  1060
#define IDC_LAYER_TXT4                  1061
#define IDC_LAYER_TXT5                  1062
#define IDC_LAYER_TXT6                  1063
#define IDC_LAYER_TXT7                  1064
#define IDC_LAYER_TXT8                  1065
#define IDC_COMPILE                     1068
#define IDC_PBUFFER_SPIN                1068
#define IDC_INITIALIZE                  1068
#define IDC_WBUFFER_SPIN                1069
#define IDC_MIXER_RAMPS                 1070
#define IDC_FADETIME                    1071
#define IDC_SELECT_STREAM               1072
#define IDC_WATCHDOG_TIME               1072
#define IDC_FADE_OUT                    1072
#define IDC_SELECT_TYPE                 1073
#define IDC_EDIT                        1074
#define IDC_FADE_OUT2                   1074
#define IDC_VOLUME_CHANGE               1074
#define IDC_REPLACE                     1075
#define IDC_EDIT2                       1075
#define IDC_ADD                         1076
#define IDC_TIMEFACTOR                  1078
#define IDC_ADD_COND                    1078
#define IDC_SUBSTREAM                   1079
#define IDC_ADD_CLOCK                   1079
#define IDC_LOAD_DEVICE                 1080
#define IDC_LOAD_MIXERDATA              1081
#define IDC_DSFILE1                     1082
#define IDC_DSFILE2                     1083
#define IDC_DSFILE3                     1084
#define IDC_SELECT_VALUE                1084
#define IDC_DSFILE4                     1085
#define IDC_VALUE                       1085
#define IDC_SELECT_CONDITIONAL          1085
#define IDC_SELECT_RANGE1               1085
#define IDC_BROWSE1                     1086
#define IDC_HOUR1                       1086
#define IDC_SELECT_RANGE2               1086
#define IDC_RANGE_MAX                   1086
#define IDC_BROWSE2                     1087
#define IDC_MINUTE1                     1087
#define IDC_BROWSE3                     1088
#define IDC_SECOND1                     1088
#define IDC_BROWSE4                     1089
#define IDC_HOUR2                       1089
#define IDC_MINUTE2                     1090
#define IDC_SECOND2                     1091
#define IDC_STARTVALUE                  1092
#define IDC_HOUR_RESET                  1092
#define IDC_RESET_INTERVAL              1092
#define IDC_ENDVALUE                    1093
#define IDC_MINUTE_RESET                1093
#define IDC_NAME                        1094
#define IDC_DAY1                        1095
#define IDC_STARTVALUE2                 1095
#define IDC_MONTH1                      1096
#define IDC_ENDVALUE2                   1096
#define IDC_CHANNEL                     1096
#define IDC_DAY2                        1097
#define IDC_MONTH2                      1098
#define IDC_STARTVALUE1                 1100
#define IDC_ENDVALUE1                   1101
#define IDC_SELECT_VALUES               1103
#define IDC_VALUE_COND_PAIR             1107
#define IDC_REMOVE                      1108
#define IDC_MOVE_UP                     1109
#define IDC_UP                          1109
#define IDC_REMOVE2                     1109
#define IDC_MOVE_DOWN                   1110
#define IDC_DOWN                        1110
#define IDC_DEFAULT_VALUE               1111
#define IDC_DEFAULT                     1112
#define IDC_REMOVE_COND                 1112
#define IDC_REMOVE_CLOCK                1113
#define IDC_LOWER_LIMIT                 1114
#define IDC_UPPER_LIMIT                 1115
#define IDC_BOOL                        1115
#define IDC_FALSE                       1115
#define IDC_RADIO2                      1116
#define IDC_TRUE                        1116
#define IDC_DECREMENT                   1116
#define IDC_EVENT                       1117
#define IDC_RADIO_COUNTDURATION         1117
#define IDC_TASK                        1117
#define IDC_RBTN_TASK                   1117
#define IDC_EQUAL                       1119
#define IDC_UNEQUAL                     1120
#define IDC_SELECT_THRESHOLD            1121
#define IDC_SMALLER                     1122
#define IDC_BEFORE                      1122
#define IDC_LARGER                      1123
#define IDC_AFTER                       1123
#define IDC_SMALLEQ                     1124
#define IDC_HOUR                        1124
#define IDC_LARGEQ                      1125
#define IDC_MINUTE                      1125
#define IDC_SECOND                      1126
#define IDC_MINUTES                     1127
#define IDC_SELECT_CONDITIONALS         1129
#define IDC_SELECT_OBJECT               1130
#define IDC_FILENAME                    1131
#define IDC_SELECT_CONDITION            1131
#define IDC_SELECT_INTERVAL_START       1131
#define IDC_START_INTERVAL              1131
#define IDC_PLAY_CONDITION              1131
#define IDC_BROWSE                      1132
#define IDC_SELECT_DELAY                1132
#define IDC_LOOP_CONDITION              1132
#define IDC_VOLUME_FACTOR               1132
#define IDC_DEVICES                     1133
#define IDC_SELECT_INTERVAL_END         1133
#define IDC_END_INTERVAL                1133
#define IDC_ERROR_DIR                   1133
#define IDC_OBJECTS                     1134
#define IDC_TEMPOFACTOR                 1134
#define IDC_ERROR_BROWSE                1134
#define IDC_SHOWLIST                    1135
#define IDC_LOG_DIR                     1135
#define IDC_SHOW                        1136
#define IDC_BROWSE6                     1136
#define IDC_LOG_BROWSE                  1136
#define IDC_SELECTION                   1137
#define IDC_EDIT_CHAIN                  1141
#define IDC_CHAINLENGTH                 1142
#define IDC_SPINLENGTH                  1144
#define IDC_SET_CHAIN_PAIR              1146
#define IDC_SELECT_FOLLOWER             1147
#define IDC_CHAIN_PAIR                  1148
#define IDC_WEIGHT                      1149
#define IDC_SET_WEIGHT                  1151
#define IDC_WEIGHTED_OBJECT             1152
#define IDC_OBJECT_COND_PAIR            1153
#define IDC_DEFAULT_OBJECT              1154
#define IDC_NEW                         1155
#define IDC_SELECT_EVENT                1156
#define IDC_PRE_MESSAGES                1157
#define IDC_PLAY_MESSAGES               1158
#define IDC_POST_MESSAGES               1159
#define IDC_PRIORITY                    1160
#define IDC_LOOP_LENGTH                 1161
#define IDC_CONDITIONALS                1165
#define IDC_DEFAULT_MESSAGES            1166
#define IDC_CLOCKS                      1166
#define IDC_MESSAGELIST                 1167
#define IDC_PLAY_MESSAGE                1167
#define IDC_NOPLAY_MESSAGE              1168
#define IDC_MESSAGE                     1168
#define IDC_STOP_MESSAGE                1169
#define IDC_EDIT_MESSAGE                1169
#define IDC_SHOW_MESSAGE                1170
#define IDC_OWNER                       1173
#define IDC_SENDER                      1176
#define IDC_CURRENT_TASK                1176
#define IDC_RBTN_CURTASK                1176
#define IDC_STREAM                      1178
#define IDC_CONDITIONAL                 1180
#define IDC_SELECT_OBJECTS              1182
#define IDC_VOLUME                      1183
#define IDC_WATCHDOG_ENABLE             1185
#define IDC_EXT_TEXT1                   1190
#define IDC_EXT_TEXT2                   1191
#define IDC_EXT_TEXT3                   1192
#define IDC_EXT_TEXT4                   1193
#define IDC_EXT_TEXT5                   1194
#define IDC_EXT_TEXT6                   1195
#define IDC_EXT_TEXT7                   1196
#define IDC_EXT_TEXT8                   1197
#define IDC_EXT_TEXT9                   1198
#define IDC_EXT_TEXT10                  1199
#define IDC_EXT_TEXT11                  1200
#define IDC_EXT_TEXT12                  1201
#define IDC_EXT_TEXT13                  1202
#define IDC_EXT_TEXT14                  1203
#define IDC_EXT_TEXT15                  1204
#define IDC_EXT_TEXT16                  1205
#define IDC_SELECT_BASE                 1210
#define IDC_SELECT_DURATION             1212
#define IDC_DURATION_BY_TIME            1212
#define IDC_RESET_ENABLE                1213
#define IDC_DURATION_BY_COUNT           1213
#define IDC_HOUR_STARTUP                1214
#define IDC_MINUTE_STARTUP              1215
#define IDC_HOUR_SHUTDOWN               1216
#define IDC_MINUTE_SHUTDOWN             1217
#define IDC_RADIO_TIMEDURATION          1219
#define IDC_RADIO_CONDITION_ONLY        1220
#define IDC_LOOP_OBJECT                 1221
#define IDC_CHECK1                      1222
#define IDC_END_DISTRIBUTION            1222
#define IDC_ENABLE_FADER                1222
#define IDC_ON1                         1222
#define IDC_WEEKDAY1                    1222
#define IDC_SELECT_COUNT                1223
#define IDC_ON2                         1223
#define IDC_WEEKDAY2                    1223
#define IDC_DATA1                       1223
#define IDC_EVENT_SELECT                1224
#define IDC_ON3                         1224
#define IDC_WEEKDAY3                    1224
#define IDC_DATA2                       1224
#define IDC_EDIT_MSG                    1225
#define IDC_ON4                         1225
#define IDC_WEEKDAY4                    1225
#define IDC_REMOVE_MSG                  1226
#define IDC_ON5                         1226
#define IDC_WEEKDAY5                    1226
#define IDC_ADD_MSG                     1227
#define IDC_ON6                         1227
#define IDC_WEEKDAY6                    1227
#define IDC_ON7                         1228
#define IDC_CHECK7                      1228
#define IDC_WEEKDAY7                    1228
#define IDC_EDIT_COND                   1228
#define IDC_ON8                         1229
#define IDC_EDIT_CLOCK                  1229
#define IDC_ON9                         1230
#define IDC_CONDITIONS                  1231
#define IDC_ON10                        1231
#define IDC_ON11                        1232
#define IDC_SELECT_FACTOR               1233
#define IDC_ON12                        1233
#define IDC_ON13                        1234
#define IDC_SELECT_START                1236
#define IDC_SELECT_TASK                 1236
#define IDC_SELECT_END                  1237
#define IDC_SELECT_MSG                  1237
#define IDC_EVENT_SELECT1               1238
#define IDC_EVENT_SELECT2               1239
#define IDC_DISPLAY_LIST                1239
#define IDC_EVENT_SELECT3               1240
#define IDC_FADER_LIST                  1240
#define IDC_EVENT_SELECT4               1241
#define IDC_CURRENT_STREAM              1243
#define IDC_WATCHDOGOCXCTRL1            1246
#define IDC_BTN_DURATION                1247
#define IDC_BTN_SELECTINDEX             1248
#define IDC_REFRESH                     1249
#define IDC_RANGEMIN                    1250
#define IDC_RANGEMAX                    1251
#define IDC_BTN_INPUTVALUE              1251
#define IDC_OBJECTLIST                  1253
#define IDC_BTN_FADERVALUE              1254
#define IDC_PLAYOBJECTS                 1257
#define IDC_TESTVALUE_BTN               1258
#define IDC_LOWERVALUE_BTN              1259
#define IDC_UPPERVALUE_BTN              1260
#define IDC_THRESHOLD_BTN               1260
#define IDC_VALUE_LIST                  1261
#define IDC_SELECT_VOLUME               1262
#define IDC_BUTTON1                     1263
#define IDC_SOFTREBOOT                  1263
#define IDC_FILTER                      1263
#define IDC_DURATION_BTN                1264
#define IDC_RBTN_CURSTREAM              1265
#define IDC_RBTN_STREAM                 1266
#define IDC_VALUES                      1267
#define IDC_COND_VALUE_LIST             1268
#define IDC_RANGE_MIN                   1270
#define IDC_SOURCE_VALUE                1271
#define IDC_DMX_DEVICES                 1272
#define IDC_DS_DEVICE                   1273
#define IDC_WAV_DEVICE                  1274
#define IDC_COND_OBJECT_LIST            1275
#define IDC_WEIGHT_LIST                 1276
#define IDC_CHAIN_LIST                  1278
#define IDC_DUMP_DIR                    1280
#define IDC_DUMP_BROWSE                 1281
#define IDC_SELECT_INPUT                1282
#define IDC_ADDRESS                     1283
#define IDC_UPDATEINT                   1284
#define IDC_INPUT_VALUE                 1285
#define IDC_DATA1_HIGH                  1285
#define IDC_PORT                        1286
#define IDC_INPUT_CONDITIONAL           1287
#define IDC_COND1                       1288
#define IDC_DATA1_LOW                   1288
#define IDC_COND2                       1289
#define IDC_COMBO1                      1289
#define IDC_COND3                       1290
#define IDC_DATA2_HIGH                  1290
#define IDC_COND4                       1291
#define IDC_DATA2_LOW                   1291
#define IDC_COND5                       1292
#define IDC_CHANNEL_LOW                 1292
#define IDC_COND6                       1293
#define IDC_CHANNEL_HIGH                1293
#define IDC_COND7                       1294
#define IDC_FADE_IN                     1294
#define IDC_COND8                       1295
#define IDC_COMBO                       1295
#define IDC_COND9                       1296
#define IDC_DATETIMEPICKER1             1296
#define IDC_TIMEPICKER                  1296
#define IDC_TIMEOFDAY                   1296
#define IDC_COND10                      1297
#define IDC_LIST1                       1297
#define IDC_TRIGGERS                    1297
#define IDC_COND11                      1298
#define IDC_ADD_TRIGGER                 1298
#define IDC_COND12                      1299
#define IDC_REMOVE_TRIGGER              1299
#define IDC_COND13                      1300
#define IDC_STARTTIME                   1300
#define IDC_STOPTIME                    1301
#define IDC_ENABLE_INTERVAL             1302
#define IDC_EMPTYACTION                 1303
#define IDC_EMPTYACTION2                1304
#define IDC_STARTACTION                 1304
#define IDC_RESET_TIMEUNIT              1305
#define IDC_WATCHDOG_TYPE               1306
#define IDC_TIMER_RES                   1307
#define IDC_ENVELOPE_RES                1308
#define IDC_BUTTON2                     1309
#define IDC_TESTWATCHDOG                1309
#define IDC_HARDREBOOT                  1309
#define IDC_SELECT_STRING               1310
#define IDC_STRING                      1311
#define IDC_STRINGS                     1312
#define IDC_ALPHABET                    1313
#define IDC_FOLDER                      1315
#define IDC_INCREMENT                   1316
#define IDC_SETVALUE                    1317
#define IDC_BTN_STATEVALUE              1318
#define IDC_SELECTPORT                  1319
#define ID_LAYER_SETUP                  32771
#define ID_STREAMS                      32771
#define ID_AUDIO_SETTINGS               32772
#define ID_TIME_SETTINGS                32773
#define ID_DEVICE_SETTINGS              32774
#define ID_VALUES                       32775
#define ID_CONDITIONALS                 32776
#define ID_SOUND_OBJECTS                32777
#define ID_SOUND_EVENTS                 32778
#define ID_INITIAL_EVENTS               32779
#define ID_STANDARD_EVENTS              32780
#define ID_TRIGGER_EVENTS               32780
#define ID_CLOCK_EVENTS                 32781
#define ID_SETTINGS_STARTUPSHUTDOWN     32783
#define ID_EDIT_DISPLAY                 32784
#define ID_TASKLIST_INITIAL2            32786
#define ID_TASKLIST_CLOCK2              32788
#define ID_TASKLIST_TRIGGER2            32789
#define ID_SETTINGS_RESET               32791
#define ID_SETTINGS_PREFERENCES         32792
#define ID_EDIT_STRINGS                 32793
#define IDS_MIDIOPEN_FAIL               61204
#define IDS_MIDICLOSE_FAIL              61205
#define IDS_TIMEOPEN_FAIL               61206
#define IDS_IMPORTMIDI                  61575
#define IDS_MIDIFIL                     61576
#define IDS_MIDIFILFORMAT               61577
#define IDS_MIDITIDFORMAT               61578
#define IDS_MIDISPOR                    61579
#define IDS_SPORANTALL                  61580
#define IDS_MIDIFILTOM                  61581
#define IDS_MIDISLUTT                   61582
#define IDS_FAILOPEN_DSCONTROL          61583
#define IDS_FAILREAD_DSCONTROL          61584
#define IDS_FAIL_CREATEBUFFER           61585
#define IDS_FAIL_TIMERCAPS              61586
#define IDS_TIME_INTERVAL               61587
#define IDS_FAIL_INITDS                 61588
#define IDS_FAIL_OPEN_MIDILIST          61589
#define IDS_FAIL_READ_MIDILIST          61590
#define IDS_WARNING_READ_MIDILIST       61591
#define IDS_FAIL_WATCHDOG               61592
#define IDS_FAILOPEN_DMXSELECTFILE      61593
#define IDS_FAILREAD_DMXSELECTFILE      61594

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        252
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1320
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
