#if !defined(AFX_WATCHDOG_OCX_H__0F071656_4350_409E_9CDA_07F02F09A807__INCLUDED_)
#define AFX_WATCHDOG_OCX_H__0F071656_4350_409E_9CDA_07F02F09A807__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWatchDog_OCX wrapper class

class CWatchDog_OCX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CWatchDog_OCX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8da24ff8, 0xb69f, 0x4a45, { 0x8c, 0x5c, 0x60, 0x23, 0x68, 0xd7, 0xae, 0x53 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, unsigned int nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, unsigned int nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long Disable();
	long EnableorLoad();
	long SetTimeUnit(long TimeUnit);
	long SetCounter(long Counter);
	long PowerON();
	long PowerOFF();
	long EnablePCIReset(BOOL Status);
	long GetCounter();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WATCHDOG_OCX_H__0F071656_4350_409E_9CDA_07F02F09A807__INCLUDED_)
